#!/bin/bash

set -e

function migrate {
    set +e

    echo "Running migrations"
    local result=1
    local counter=1
    local num_retries=10
    while [[ $counter -le $num_retries ]]; do
      echo "Running migration try number ${counter} of ${num_retries}"
      bundle exec rake db:migrate
      result=$?
      if [[ $result -eq 0 ]]; then
        break
      fi
      sleep 5
      ((counter++))
    done

    if [[ $result -ne 0 ]]; then
      echo "Migrations failed"
      exit $result
    fi

    set -e
}

export RAILS_ENV=production
export RAILS_LOG_TO_STDOUT=true
export DATABASE_URL=postgres://<%= p("database_user") %>:<%= p("database_password") %>@127.0.0.1:5432/postfacto_production
export PATH=/var/vcap/packages/nodejs/bin:$PATH
export SECRET_KEY_BASE=<%= p("secret_key") %>
export RAILS_TMP=/var/vcap/data/postfacto
export RAILS_SERVE_STATIC_FILES=1
export USE_POSTGRES_FOR_ACTION_CABLE=true
source "${BOSH_PACKAGES_DIR:-/var/vcap/packages}/ruby-2.7.3-r0.52.0/bosh/runtime.env"

PACKAGE_DIR=/var/vcap/packages/postfacto
JOB_DIR=/var/vcap/jobs/postfacto

pushd /var/vcap/packages/postfacto
    migrate
    ADMIN_EMAIL=<%= p("admin_email") %> ADMIN_PASSWORD=<%= p("admin_password") %>  bundle exec rake admin:create_user
    exec bundle exec rails s -e $RAILS_ENV
popd

